### ISSUE TITLE
QQQ autosampler "park station failed"

### ISSUE THREAD

**Issue by curt-f** [Stanford-ChEMH-MCAC/protocols#10]
From Adam:

> The autosampler on QQQ is refusing to cooperate again. After a couple of my injections it suddenly returned error “Moving needle to park station failed [EE 25106, 202]” and “Sampler initialization failed [EE 25120, 0]”.
> I restarted it a couple of times and after doing the initialization yoga it returned the needle to the seat and popped the error again. Finally, after 6-7 restarts it seemed to be better, but when I ran my worklist again, the original issue reappeared. As of now, the QQQ analysis is impossible.
> 

From Adam 40 minutes later:

> I wouldn’t be overly optimistic, but I’ve just managed to inject a sample. I’ll keep you updated.

**Comment by curt-f** [comment]
This sounds like something that needs Agilent attention.

**Comment by curt-f** [comment]
Progress / worsening:

The needle appears slightly bent to the right when viewed head-on looking in to the autosampler.

We used Lab Advisor to try to get the needle to the "Change Needle" position, but this also caused an error.  (Our plan had been to get the needle off to bend it back or replace it, but it can't even lift the needle off of the parking station to do that.)

**Comment by curt-f** [comment]
> Confirmation: Submittal of Online Service Request Form
> 
> Submitted on: 8/17/2018 12:13:36 PM 
> 
> Thank you for successfully submitting the Online Service Request form.  An Agilent service representative will be contacting you within 1 business day in order to process your request.
> 
> Service Request Type:  On Site Repair
> Instrument Type:  Liquid Chromatography Mass Spectrometry (LCMS SQ, QQQ, TOF & QTOF)
> Instrument Model:  G7167B
> Instrument Serial Number:  DEBAS01520
> 
> Please note the following: 
> 
> *  The information collected will only be used only to facilitate the scheduling of your service call. 
> 
> *  Completion of a separate form will be necessary for each instrument requiring repair. 
> 
> *  If need to cancel / re-schedule a service call or have questions that do not pertain specifically to onsite hardware repair, please contact Agilent Customer Support at 800-227-9770 option 3. 
> 
> Regards,
> 
> Agilent Technologies
> Agilent CrossLab Group
> Services and Repair

**Comment by curt-f** [comment]
The Agilent Service Request Ref # is 8102056156 .

**Comment by wdwvt1** [comment]
just an update: Joon reports injections beyond two samples still causing the error. However, looks like his data is good enough to use so everything else working okay.

**Comment by awawro** [comment]
Today (8/20, 3–5pm) I managed to run a set of 14 samples in series of two; everything seemed to be fine. Then Will vT. and I took chances and ran a worklist of four blank injections -- again, successfully. This may require more testing, but looks promising so far.

**Comment by kimtsui** [comment]
The autosampler seem to be working well so far! It's been running for 11 samples straight so far. Hopefully it'll keep running smoothly. Thanks Adam and Will for fixing/testing it!

**Comment by curt-f** [comment]
I don't know what you guys did, but I like it.  Thanks to everyone who
helped work on this one!  The Agilent service request is open in case
anything else pops up.

**Comment by wdwvt1** [comment]
I asked them to close the ticket on this one since we've had things working without incident for a week. A suggested reset method was given by a service engineer in an email. In the future, we might try this if we have multisampler errors of the same type:

1. Within Lab Advisor, navigate to the ‘Instrument Control’ tab and expand the ‘Configuration’ section. There will be several commands available relating to the “hotel data.” Click on the button that says ‘Clear (hotel) data.’
2. Power off the multisampler.
3. Physically push the arm to the back-right corner of the sampler.
4. Power the autosampler back on.
5. Going back to Lab Advisor, navigate again to the ‘Instrument Control’ tab. This time click the ‘auto-referencing’ button and follow the on-screen prompts. This procedure will reset the calibration of the transport arm.
