### ISSUE TITLE
adaptor between DAD and QTOF needs replacing/fixing

### ISSUE THREAD

**Issue by wdwvt1** [Stanford-ChEMH-MCAC/protocols#12]
The line between the DAD and the QTOF, or the end of the column and the QTOF if you are bypassing the DAD, is not held in the connector anymore (detached state shown below). I could still get a run to start without leaking by pushing the line in hard after attaching the connector to the column but maybe a new connector is in order.
![img_20180909_170625](https://user-images.githubusercontent.com/1048569/45270983-edd34300-b457-11e8-8d37-f30f33858db7.jpg)

**Comment by curt-f** [comment]
I might be missing something, but I think that's how those plastic connectors are supposed to work.  Just thread the capillary back through the plastic ferule and screw it into where it needs to go.  Detachment is not necessarily a sign of something wrong.

**Comment by wdwvt1** [comment]
ahh okay - I thought they were supposed to lock in tight/I had never seen one come undone.

**Comment by curt-f** [comment]
(Also, that line is called the "transfer line" because it transfers material from the LC to the MS)
