### ISSUE TITLE
6470 QQQ injector failing with 96 well plates

### ISSUE THREAD

**Issue by wdwvt1** [Stanford-ChEMH-MCAC/protocols#14]
Kali reported that the multisampler on the QQQ is not injecting samples from 96 well Agilent plates. The needle fails to pierce the cover (or descend at all). Multiple people have reported that injection from 54 well vial plates is functioning properly.

**Comment by curt-f** [comment]
I think Adam W. has been injecting from the same plates as Kali, successfully.

**Comment by awawro** [comment]
I did 60 injections last night and no issues. I think Kali may have used incorrect plate layout setting: Agilent96M (at the top of the drop-down list, iirc) instead of plain Agilent96.

**Comment by curt-f** [comment]
Thanks @awawro

**Comment by curt-f** [comment]
Kali if this fixes your problem can you report back?  Also, I apologize for not even knowing there was a difference between "96M" and "96".  Lesson learned.

**Comment by wdwvt1** [comment]
Problem seems to have been improper multisampler settings. All is well.
