### ISSUE TITLE
leak and poor ionization

### ISSUE THREAD

**Issue by curt-f** [Stanford-ChEMH-MCAC/protocols#15]
From Tim H:
<blockquote>
I just wanted to warn that the QQQ is not really behaving for me--if you want to use the rest of the time I reserved, go for it!

I used a previous method and got decent data looking at full spectrum, though the ionization (positive mode) was less than with similar samples in the past. Additionally, the MCT module (with the column) was leaking from port 3, despite port 3 not being part of the selected column position.

I'm not sure if you guys have seen these issues before and know how to resolve them!
</blockquote>

**Comment by tentrillion** [comment]
Any updates here from any users?  The ion-pairing LC runs have gone OK so far this week, at least as judged by the lack of anyone complaining to me yet.

**Comment by awawro** [comment]
I ran my QC samples on Thursday and was unable to see the signals (MRM, various basic polar compounds at 200 nM, HILIC column). Purging the column did not help.

After consulting the Agilent engineer who came to fix the ion-paring LC on Friday, Will vT and I cleaned the nebulizer, the spray shield and the capillary according to Agilent's protocol. That required venting the MS; we pumped it down back to regular pressure on Friday night (rough vac 1.8E+0 Torr, high vac 1.3E-5).

Then I ran my QC samples again, but no change whatsoever. Today Qi switched to ion-pairing mode and reported not detecting his samples either (not sure, but most likely by MRM).

I just started the QQQ in MS2 scan mode (remotely) and it seemed to be detecting the usual background contaminants quite well. I'm wondering if the issue affects MRM exclusively (Q1?), but I won't be able to check that during the weekend.

**Comment by curt-f** [comment]
The MS does not seem to have any sensitivity at lower m/z ranges; multiple users are reporting complete failures to detect their analytes.  Full-scan runs also failed to show any signal, and autotune (with fresh calibration mix) failed too.  Agilent is being notified.

BTW, @awawro's submissions to this thread are thorough and supremely informative; they should be a model we all keep in mind for reporting issues.

**Comment by awawro** [comment]
I replaced the capillary and tuned the QQQ. Checktune report looks fine now (see below).
My HILIC QCs are way better now -- clear detection of <0.5 pmol injections of creatine.

I will run a plate of samples today and report results here.

[01232018_checktune2.pdf](https://github.com/Stanford-ChEMH-MCAC/protocols/files/2793344/01232018_checktune2.pdf)

**Comment by wdwvt1** [comment]
🌟🌟🌟

**Comment by awawro** [comment]
Everything looks fine; drifting, but consistent ISTD area vs. injection number. 2nd experiment has larger variability because of high concentrations of non-labeled creatine co-eluting, but you can see creatine-free samples every 6-8 injections. 
ISTD: creatine-d3, 0.5 uM, 5 uL injected, 2.5 pmol/injection

![aw_120_2_istd](https://user-images.githubusercontent.com/37852568/51778555-32821280-20b7-11e9-8a6e-f800db5a29e0.png)

![aw_121_2_istd](https://user-images.githubusercontent.com/37852568/51778565-44fc4c00-20b7-11e9-9bb3-c0dd069b8d1d.png)

**Comment by curt-f** [comment]
The new capillary (well, not new, but previously used) that I bummed from an Agilent FSE who happened to be visiting the Fischbach lab seems to have done the trick here.  There are now backup spare capillaries by both the qTOF and QQQ in case this crops up again.
