### ISSUE TITLE
Bent inlet to port #3 on 2-way 6-port column switching valve

### ISSUE THREAD

**Issue by curt-f** [Stanford-ChEMH-MCAC/protocols#16]
Last weekend, several users (thanks Kim and Joon!) reported issues with a capillary.  The capillary ferrule was bent where it connected to the switching valve (at port #3).  We installed a new capillary at port #3, but there was still a leak.  Removing the new capillary revealed it was also bent in the same way as the old one.  Our theory is that the port #3 inlet is permanently bent and will bend and destroy any capillaries connected to ti.  

Planned solution: order a new valve faceplate.

**Comment by curt-f** [comment]
Joon helped troubleshoot this issue and pinpoint a replacement part:

<blockquote>
I called Agilent and the part that needs replacement is called the strator head (5068-0006). This is just the metal piece in the front where the capillaries screw in. I wonder if the piece can be repaired or if we could program it to use an alternative valve bc the piece seems to be pricy (~$1150). I also talked to the next person on the QQQ about it. Please let me know! Thanks for the help.
</blockquote>

**Comment by curt-f** [comment]
From my dear friend `OF1_PRD Workflow Mailer`:

<blockquote>
PO Number  : 61970283                                                                                                             
PO Total   :          949.45                                                                                                       
PO Desc    : Stator for 2 position /6 port ultra high pressure valve head 1200bar                                                 
PO Detail  : https://ofweb.stanford.edu/apex/f?p=325:3:::NO:RP%2C3:P3_PO_NO:61970283                                               
Req Number : 4684023                                                                                                               
Req Total  :          949.45                                                                                                       
Req Desc   : <same as PO>       
</blockquote>

**Comment by curt-f** [comment]
My only theory on how the inlet could be bent so badly would be that at some point, someone **overtightened** this connection.  Please remember Tony L.'s advice -- if there's a leak, tighten a (non-quick-connect) connection by 1/8th of a turn, then check to see if the leak went away.  Don't tighten more than this in one go.

**Comment by tentrillion** [comment]
The replacement part came in and I put it on the instrument.  The next folks to use the non-ion pairing LC should verify that it functions properly.

**Comment by awawro** [comment]
6-way switching valve port 3 needed to be tightened a little, but it seems to work well now.
