### ISSUE TITLE
pump ripple and pressure deviations on 6545

### ISSUE THREAD

**Issue by wdwvt1** [Stanford-ChEMH-MCAC/protocols#17]
The `6545` is experiencing bad pump ripple. Anecdotally I have noticed that

 1. Whenever I switch buffer in line `A2` and draw up any reasonably sized air bubble I'll get pump ripple (two different days with different magnitudes below).
 2. The ripple is smaller without a column (the ~25 bar ripples on the right of the top screenshot are without a column) but still present. 
 3. The percentage of `A2` that is flowing affects the period of the ripple (as does the overall pressure). 

![bounce_wo_column](https://user-images.githubusercontent.com/1048569/49470598-616abf00-f7bf-11e8-9b7f-aa44cb0310c4.PNG)
![ripple_03](https://user-images.githubusercontent.com/1048569/49470604-64fe4600-f7bf-11e8-956f-7160bb9b8175.PNG)

I have had success resolving this by: putting my column in, turning the flow on, turning the pump conditioning on for ~5 minutes, and then turning it off. I have to repeat this cycle several times, and frequently have had to alter the composition of the flow to get the ripple to go away. 

However, as of today, I can resolve the ripple but the column pressure has lost a lot of stability. 
Below, the blue trace is an expected pressure curve and the green trace is what I am seeing. 

![screen shot 2018-12-04 at 13 01 56](https://user-images.githubusercontent.com/1048569/49472670-da204a00-f7c4-11e8-8112-792856a8a629.png)

I have done the `Stuck Inlet Valve` cleaning procedure, but it has not resolved the problem. 

Leaving this here in case others are experiencing this problem/know something dumb I am doing.

**Comment by wdwvt1** [comment]
I ran the `Pump Leak Rate Test` in Lab Advisor. Pump B failed as shown in the screenshot below. Unsure how important this is to the situation, but reading suggested a malfunctioning seal on a pump as a possible cause od ripple/instability.
![leak_test](https://user-images.githubusercontent.com/1048569/49483523-5415fa80-f7e8-11e8-8ab2-9301ed377db6.PNG)

**Comment by tentrillion** [comment]
If the problem happens only when you inject samples, I don't think it's a pump seal issue.  (Might be wrong though.)  Perhaps something is wrong with the degasser.

**Comment by tentrillion** [comment]
Can you call Agilent and ask for their advice?

**Comment by tentrillion** [comment]
I just ran the system at 50% A2 and 50% B2 for 5 minutes and noticed no ripple.  Then I injected the QC standard and it seems like it is working fine -- I see peaks, I see good MS intensity, and I see no pressure ripple.  
![screen shot 2018-12-05 at 08 33 08](https://user-images.githubusercontent.com/11185141/49528242-751e3000-f868-11e8-8ca5-59c678fe0d33.png)

**Comment by tentrillion** [comment]
Pretty sure we have new pump seals in the cabinet under the MS.  It's been awhile since I've changed pump seals on a system but if you want to give it a go with me let me know.
