### ISSUE TITLE
Multisampler bottom valve leak on ion pairing UHPLC

### ISSUE THREAD

**Issue by liuqichem** [Stanford-ChEMH-MCAC/protocols#18]
Multisampler bottom 8-port valve leaks. I can see drops coming out between the seal (~ 1 drops/10 min at a 0.25 mL/min flow rate. I have tried to loosen and retighten the two screws, but still could not stop leaking. I ran the Pump Leak Rate Test in Lab Advisor according to will's report, both pump A and B passed the test. However, my compounds' retention time shifted for ~ 1 mins.

**Comment by curt-f** [comment]
This was the initial report of https://github.com/Stanford-ChEMH-MCAC/protocols/issues/19 ; that leak is reportedly fixed now.
