### ISSUE TITLE
document error messages and resolution

### ISSUE THREAD

**Issue by wdwvt1** [Stanford-ChEMH-MCAC/protocols#2]
Error messages on the 6545 and 6740 are usually cryptic. The manuals don't usually reference the specific error codes and chromacademy and other chromatography forums aren't usually that helpful. Would it be reasonable to encourage users of the MCAC instruments to post their exact error messages (sending screenshots to our email if they are unfamiliar with github) and what resolved them? This would be helpful both for other MCAC users and for the broader community.

**Comment by tentrillion** [comment]
Good idea.  What do you think is the best format?  Here on Github?  Slack (do we need a slack?)?  Google Sheet?

**Comment by curt-f** [comment]
We've begun doing this: thanks again to @wdwvt1 for the idea.  I'm closing this one for now, but Will, feel free to re-open if you feel the format or structure needs refinement.
