### ISSUE TITLE
whining turbomolecular pump on the 6545

### ISSUE THREAD

**Issue by curt-f** [Stanford-ChEMH-MCAC/protocols#33]
The instrument is making intermittent, very loud, very high-pitched whines.  This indicates that one of the turbopumps is nearing the end of its life.  I've called this into Agilent.  Servie request number 8102667011 and service order number 6003486699.  Repairs are currently scheduled for Mon 7 October and Tue 8 October, but based on past experience someone will likely be out sooner than this.  

A potential temporary fix to prolong the turbo we have is to vent the system, let the turbos stop spinning, and then restart them (i.e. pump back down).  I'd like to try this as soon as convenient.

**Comment by tentrillion** [comment]
Ron Lim came today to replace Turbo1, the front-end turbo for the octopole, quadrupole, etc.  It is more heavily burdened than the TOF turbo, and plus Turbo2 the TOF turbo was replaced last September.
