### ISSUE TITLE
TeamViewer alternatives

### ISSUE THREAD

**Issue by tentrillion** [Stanford-ChEMH-MCAC/protocols#6]
We are in the hunt for alternatives to TeamViewer.  

Does anyone have any recommendations on a freely-available, Windows-compatible and Stanford IT-compatible remote access software?  I know of Windows's old Remote Desktop but am curious if anyone has newer recs.

Curt

**Comment by curt-f** [comment]
Programs floated by Soumaya:

* https://www.lifewire.com/aeroadmin-review-2625152

* https://www.lifewire.com/anydesk-review-2625154

**Comment by curt-f** [comment]
From Ariel, it seems that Microsoft Remote Access is used in the Fischbach lab and all that is required is some firewall exception requests placed with Stanford IT.

**Comment by curt-f** [comment]
Sent email to team:

> An update on our TeamViewer situation:
> 
> Several folks weighed in with potential replacements.  Thanks to all you!  Reports are that TeamViewer performance continues to degenerate.
> 
> Based on suggestions, I've installed AnyDesk on the qTOF on a trial basis.  I've verified that it works.  You can connect to the qTOF at AnyDesk Address "173 073 489".  AnyDesk appears Mac and PC compatible.  I'm not sure about mobile phones.  (The password for qTOF access is unchanged from before.)
> 
> https://anydesk.com/remote-desktop
> 
> Give it a try.  In a few days if it seems to work well, I'll install it on everything.  I'd welcome thoughts and feedback at https://github.com/Stanford-ChEMH-MCAC/protocols/issues/6

**Comment by curt-f** [comment]
AnyDesk has also been installed on the QQQ computer for some time.  It seems to be working well.
